### ISSUE TITLE
Xarray-simlab 0.4 related updates

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscape#13]
- [x] define static variables (grid processes, maybe elsewhere like stratigraphic horizons) #14
- [x] index variables (grid processes, maybe elsewhere like stratigraphic horizons) #14
- [x] use multiple groups for some variables #15
- [x] object variables? 04ea2d530b9fed28691accc4b23702974a20b0c6
- [x] fix compatibility with dask.distributed -> can't pickle fortran objects #16
  - Avoid using ``fastscapelib_fortran.fastscapecontext`` directly -> declare instead all variables that we need (tedious, verbose but at least those are serializable).

Nice to have:

- [x] default values (e.g., SPL "n" and "m" exponents, maybe other parameters) 
- [x] values validators (ranges, choices, etc.)
